### ISSUE TITLE
Upgrade to Filament 3

### ISSUE THREAD

**Issue by a21ns1g4ts** [archilex/filament-toggle-icon-column#23]

**Comment by archilex** [comment]
This is compatible with Filament v3. Are you having a specific issue?

**Comment by a21ns1g4ts** [comment]
@archilex Maybe we need update our composer.json 
![image](https://github.com/archilex/filament-toggle-icon-column/assets/11599205/73e6b2cf-2c97-48a8-926f-b91636331cec)

**Comment by archilex** [comment]
That's the `composer.json` file for v1 (which is compatible with Filament v2). the 2.x branch is for Filament v3. I still v2 in beta which may be the issues you are encountering. To bring in a beta package, you need to bump `toggle-icon-column` in your composer.json to `^v2.0` then make sure you have `minimum-stability` set to `dev`.

That said, I'll go ahead and take this out of beta so it should pull in correctly.

**Comment by a21ns1g4ts** [comment]
@archilex Thanks for your reliese :rocket:

**Comment by archilex** [comment]
@a21ns1g4ts I just tagged a 3.0 release to match Filament and avoid confusion. So be sure 3.0 pulls down instead. Thanks!
